controllers:
    resource: ../src/Controller/
    type: attribute

app_register:
    path: /register
    controller: App\Controller\SecurityController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

